site_name: Devity Docs
site_url: https://docs.devity.in
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: "#1C1536"  # Corrected primary color
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: "#1C1536"
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  features:
    - search.suggest
    - search.highlight
    - search.share

nav:
  - Home: index.md
  - Getting Started:
    - Overview: getting-started/index.md
    - Flutter SDK: getting-started/flutter_sdk.md
  - Core Concepts:
    - Overview: core-concepts/index.md
    - Specs & Workflows: core-concepts/specs_and_workflows.md
    - Renderers & Layouts: core-concepts/renderers_layouts.md
    - Widgets: core-concepts/widgets.md
    - Actions & Events: core-concepts/actions_events.md
    - Data Binding: core-concepts/data_binding.md
    - Expressions: core-concepts/expressions.md
    - Rules: core-concepts/rules.md
    - Styling: core-concepts/styling.md
  - Reference:
    - Overview: reference/index.md
    - Console Guide: reference/console_guide.md
    - Spec Schema: reference/spec_schema.md
    - Component Library:
      - Overview: reference/components/index.md
      - Renderers:
        - Overview: reference/components/renderers/index.md
        - Column: reference/components/renderers/column.md
        # - Row: reference/components/renderers/row.md # Add others as created
      - Widgets:
        - Overview: reference/components/widgets/index.md
        - Text: reference/components/widgets/text.md
        # - Button: reference/components/widgets/button.md # Add others as created
      - Actions:
        - Overview: reference/components/actions/index.md
        - Navigate: reference/components/actions/navigate.md
        # - ApiCall: reference/components/actions/apicall.md # Add others as created
    - Flutter SDK API: reference/flutter_sdk_api.md
    - Backend API Design: reference/backend_api_design.md
  - Tutorials:
    - Overview: tutorials/index.md
    - Building a Login Form: tutorials/building_a_login_form.md
  - Advanced:
    - Overview: advanced/index.md
    - Custom Widgets: advanced/custom_widgets.md
    - Custom Actions: advanced/custom_actions.md
    - AI Assistant Usage: advanced/ai_assistant.md
    - Deployment Strategies: advanced/deployment.md
  - Architecture: architecture.md
  - Security: security.md
  - FAQ: faq.md

extra:
  features:
    - navigation.instant  # Faster page loads
    - navigation.tracking # Update URL as you scroll
    - navigation.tabs
    - navigation.sections
    - navigation.expand   # Expand menu by default
    - content.code.copy   # Copy button for code blocks 
    - content.code.select # Selectable code blocks
    - content.code.annotate # Annotate code blocks
    - content.tabs.link
    - toc.follow          # Keep Table of Contents visible
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/devity-in
    - icon: fontawesome/brands/twitter
      link: https://x.com/devity_in?mx=2
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/devity-in
